---
- name: nginx reloaded
  service:
    name: nginx
    state: reloaded

- name: nginx restart
  service:
    name: nginx
    state: restarted

- name: nginx started
  service:
    name: nginx
    state: started
    enabled: true

- name: fail2ban restart
  service:
    name: fail2ban
    state: restarted
