---
- name: Nginx | GPG Key
  when: ansible_distribution == 'Debian'
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key

- name: Nginx | Debian repository
  when: ansible_distribution == 'Debian'
  apt_repository:
    repo: '{{item}}'
    state: present
  with_items:
    - deb https://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx
    - deb-src https://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx

- name: Nginx | Install
  apt:
    name: nginx
    state: present
  notify: nginx started

- name: Nginx | création de /etc/nginx/sites-enabled
  file:
    state: directory
    path: /etc/nginx/sites-enabled

- name: Nginx | création de /etc/nginx/sites-available
  file:
    state: directory
    path: /etc/nginx/sites-available

- name: Nginx | Default Vhost
  template:
    src: default.j2
    dest: '/etc/nginx/sites-available/default'

- name: Nginx | création de /etc/nginx/nginxconfig.io
  file: state=directory path=/etc/nginx/nginxconfig.io

- name: Nginx | nginx.conf
  template:
    src: '{{ item }}.j2'
    dest: '/etc/nginx/{{item}}'
  loop:
    - nginx.conf
    - nginxconfig.io/general.conf
    - nginxconfig.io/proxy.conf
    - nginxconfig.io/security.conf

- name: 'Nginx | Vhost {{ domain }}'
  template:
    src: vhost.j2
    dest: '/etc/nginx/sites-available/{{ domain }}'
  notify: nginx reloaded

- name: 'Nginx | Vhost {{ domain }}'
  become: yes
  file:
    path: '/etc/nginx/sites-enabled/{{ domain }}'
    src: '/etc/nginx/sites-available/{{ domain }}'
    state: link
  notify: nginx reloaded
